// Generated by CoffeeScript 1.6.3
var controllers, notify;

notify = angular.module('notify', ['ngRoute', 'controllers']);

notify.config([
  '$routeProvider', function($routeProvider) {
    return $routeProvider.when('/', {
      templateUrl: 'partials/index.html',
      controller: 'HomePageCtrl'
    }).otherwise({
      redirectTo: '/'
    });
  }
]);

controllers = angular.module('controllers', []);

controllers.controller('HomePageCtrl', [
  '$scope', '$http', function($scope, $http) {
    $scope.input = {
      category: '',
      query: ''
    };
    $http({
      method: 'GET',
      url: '/api/search/categories/'
    }).success(function(data) {
      $scope.categories = data.categories;
      return $scope.input.category = data.categories[0];
    });
    return $scope.search = function() {
      $http.get('/api/search', {
        params: {
          'query': $scope.input.query,
          'category': $scope.input.category
        }
      }).success(function(data) {
        return $scope.results = data.results;
      });
      return console.log($scope.input);
    };
  }
]);
