// Generated by CoffeeScript 1.6.3
var controllers, notify;

notify = angular.module('notify', ['ngRoute', 'controllers']);

notify.config([
  '$routeProvider', function($routeProvider) {
    return $routeProvider.when('/', {
      templateUrl: 'partials/index.html',
      controller: 'HomePageCtrl'
    }).otherwise({
      redirectTo: '/'
    });
  }
]);

controllers = angular.module('controllers', []);

controllers.controller('HomePageCtrl', [
  '$scope', '$http', function($scope, $http) {
    $scope.input = {
      category: '',
      query: ''
    };
    $http({
      method: 'GET',
      url: '/api/get_categories'
    }).success(function(data) {
      var cat;
      $scope.categories = (function() {
        var _results;
        _results = [];
        for (cat in data.categories) {
          _results.push(cat);
        }
        return _results;
      })();
      return console.log($scope.categories);
    });
    $scope.submit = function() {
      $http.get('/api/search', {
        params: {
          'query': $scope.input.query,
          'category': $scope.input.category
        }
      }).success(function(data) {
        return $scope.results = data.results;
      });
      return console.log($scope.input);
    };
    return $scope.submit_email = function() {
      $http.get('/api/send_search_results', {
        params: {
          'query': $scope.input.query,
          'category': $scope.input.category,
          'email_address': $scope.input.email_address
        }
      }).success(function(data) {
        return $scope.results = data.results;
      });
      return console.log($scope.input);
    };
  }
]);
