locations = [
"South Africa.Gauteng.Pretoria / Tshwane",
"South Africa.KwaZulu-Natal.Drakensberg",
"South Africa.Gauteng.Sedibeng",
"South Africa.Western Cape.Cape Flats",
"South Africa.KwaZulu-Natal.South Coast (Ugu)",
"South Africa.Mpumalanga.Ehlanzeni",
"South Africa.Free State.Southern",
"South Africa.KwaZulu-Natal.Midlands",
"South Africa.Limpopo.Polokwane",
"South Africa.Gauteng",
"South Africa.Free State.Goldfields",
"South Africa.Eastern Cape.Wild Coast & Berg",
"South Africa.Free State.Northern",
"South Africa.North West.Molema",
"South Africa.Western Cape.Overberg",
"South Africa.Northern Cape.Namakwa",
"South Africa.Mpumalanga.Wetland & Ermelo",
"South Africa.Gauteng.East Rand",
"South Africa.Northern Cape.Green Kalahari",
"South Africa.Western Cape.Atlantic Seaboard",
"South Africa.Western Cape",
"South Africa.Western Cape.Southern Peninsula",
"South Africa.KwaZulu-Natal.Durban City",
"South Africa.Eastern Cape.Western Region",
"South Africa.KwaZulu-Natal.North Suburbs",
"South Africa.Mpumalanga",
"South Africa.Northern Cape.Kalahari",
"South Africa.Western Cape.West Coast",
"South Africa.Free State",
"South Africa.Mpumalanga.Heartland - Cosmos Country",
"South Africa.Northern Cape.Upper Karoo",
"South Africa.Limpopo",
"South Africa.North West.Bojanala",
"South Africa.Free State.Eastern",
"South Africa.Western Cape.Northern Suburbs",
"South Africa.Gauteng.Johannesburg",
"South Africa.North West",
"South Africa.KwaZulu-Natal.North Coast",
"South Africa.Western Cape.Helderberg",
"South Africa.Limpopo.Musina",
"South Africa.Western Cape.Southern Suburbs",
"South Africa.Eastern Cape.Amatola",
"South Africa.KwaZulu-Natal.South Suburbs",
"South Africa.Western Cape.Cape Winelands",
"South Africa.Eastern Cape",
"South Africa.Limpopo.Phalaborwa",
"South Africa.Gauteng.West Rand",
"South Africa.North West.Kaunda",
"South Africa.Northern Cape.Hantam Karoo",
"South Africa.Western Cape.Central Karoo",
"South Africa",
"South Africa.KwaZulu-Natal",
"South Africa.Northern Cape",
"South Africa.Western Cape.Cape Town",
"South Africa.Mpumalanga.Highland",
"South Africa.Limpopo.Modimolle",
"South Africa.Limpopo.Louis Trichardt",
"South Africa.North West.Mompati",
"South Africa.Limpopo.Tzaneen",
"South Africa.Limpopo.Other",
"South Africa.Northern Cape.Diamond Fields",
"South Africa.Western Cape.Eden",
"South Africa.KwaZulu-Natal.West Suburbs",
]
