searcher_gumtree_category_map = {
"All Categories.Property.Short Term":"Short Term",
"All Categories.Services.DJ & Entertainment services":"DJ & Entertainment services",
"All Categories.Automotive Vehicles.Caravan & RVs":"Caravan & RVs",
"All Categories.Fashion.Jewellery & Watches":"Jewellery & Watches",
"All Categories.Jobs.Sports Club jobs":"Sports Club jobs",
"All Categories.Services.Tax & Financial services":"Tax & Financial services",
"All Categories.Property.Car Parks & Storage":"Car Parks & Storage",
"All Categories.Jobs.Engineering & Architecture jobs":"Engineering & Architecture jobs",
"All Categories.Electronics.Other Electronics":"Other Electronics",
"All Categories.Jobs.Childcare & Babysitting jobs":"Childcare & Babysitting jobs",
"All Categories.Job Seekers.Childcare & Babysitting CVs":"Childcare & Babysitting CVs",
"All Categories.Fashion.Shoes":"Shoes",
"All Categories.Job Seekers.Computing & IT CVs":"Computing & IT CVs",
"All Categories.Sports & Leisure.Musical Instruments":"Musical Instruments",
"All Categories.Services.Real estate services":"Real estate services",
"All Categories.Pets.Fish":"Fish",
"All Categories.Automotive Vehicles.Heavy trucks & machinery":"Heavy trucks & machinery",
"All Categories.Pets.Reptiles":"Reptiles",
"All Categories.Job Seekers.Manual Labour CVs":"Manual Labour CVs",
"All Categories.Job Seekers.Office Work CVs":"Office Work CVs",
"All Categories.Business-to-Business.Industrial Machinery":"Industrial Machinery",
"All Categories.Home & Garden.Home appliances":"Home appliances",
"All Categories.Jobs.Banking jobs":"Banking jobs",
"All Categories.Jobs.Internship jobs":"Internship jobs",
"All Categories.Services.Fitness & Personal Training services":"Fitness & Personal Training services",
"All Categories.Home & Garden.Antiques & Collectables":"Antiques & Collectables",
"All Categories.Services.Recruitment services":"Recruitment services",
"All Categories.Services.Wedding Venues & services":"Wedding Venues & services",
"All Categories.Automotive Vehicles.Cars":"Cars",
"All Categories.Property.Houses & Flats For Rent":"Houses & Flats For Rent",
"All Categories.Jobs.Healthcare & Nursing jobs":"Healthcare & Nursing jobs",
"All Categories.Services.Event Services":"Event Services",
"All Categories.Services.Photography & Video services":"Photography & Video services",
"All Categories.Jobs.Clerical & Administrative jobs":"Clerical & Administrative jobs",
"All Categories.Community.Language Courses & Training":"Language Courses & Training",
"All Categories.Home & Garden.Garden & Braai":"Garden & Braai",
"All Categories.Home & Garden.DIY & Tools":"DIY & Tools",
"All Categories.Job Seekers.Mining Industry CVs":"Mining Industry CVs",
"All Categories.Baby & Kids.Car Seats & Travel":"Car Seats & Travel",
"All Categories.Sports & Leisure":"Sports & Leisure",
"All Categories.Services":"Services",
"All Categories.Community":"Community",
"All Categories.Services.Courses & Training":"Courses & Training",
"All Categories.Fashion.Clothing":"Clothing",
"All Categories.Events":"Events",
"All Categories.Jobs.Office jobs":"Office jobs",
"All Categories.Fashion.Wedding Wear":"Wedding Wear",
"All Categories.Pets.Pet Accessories":"Pet Accessories",
"All Categories.Property.Land & Plots For Sale":"Land & Plots For Sale",
"All Categories.Jobs.Hotel Jobs":"Hotel Jobs",
"All Categories.Services.Cleaning Services":"Cleaning Services",
"All Categories.Services.Manufacturing":"Manufacturing",
"All Categories.Services.Pet Services":"Pet Services",
"All Categories.Jobs.Sales & Telemarketing jobs":"Sales & Telemarketing jobs",
"All Categories.Job Seekers.Engineering & Architecture CVs":"Engineering & Architecture CVs",
"All Categories.Jobs.Manual Labour jobs":"Manual Labour jobs",
"All Categories.Community.Other":"Other",
"All Categories.Baby & Kids.Toys":"Toys",
"All Categories.Baby & Kids":"Baby & Kids",
"All Categories.Jobs.Housekeeping & Cleaning jobs":"Housekeeping & Cleaning jobs",
"All Categories.Job Seekers.Customer Service CVs":"Customer Service CVs",
"All Categories.Job Seekers.General Worker CVs":"General Worker CVs",
"All Categories.Electronics.Mobile Phones & Telephones":"Mobile Phones & Telephones",
"All Categories.Services.Automotive Services":"Automotive Services",
"All Categories.Automotive Vehicles":"Automotive Vehicles",
"All Categories.Job Seekers.Healthcare & Nursing CVs":"Healthcare & Nursing CVs",
"All Categories.Property":"Property",
"All Categories.Business-to-Business.Store & Catering Equipment":"Store & Catering Equipment",
"All Categories.Jobs.Mining Industry jobs":"Mining Industry jobs",
"All Categories.Jobs.Logistics & Transportation jobs":"Logistics & Transportation jobs",
"All Categories.Events.Other":"Other",
"All Categories.Job Seekers.Logistics & Transportation CVs":"Logistics & Transportation CVs",
"All Categories.Services.Chauffeur & Airport transfer":"Chauffeur & Airport transfer",
"All Categories.Job Seekers.Legal Work CVs":"Legal Work CVs",
"All Categories.Property.Houses & Flats For Sale":"Houses & Flats For Sale",
"All Categories.Job Seekers.Clerical & Administrative CVs":"Clerical & Administrative CVs",
"All Categories":"All Categories",
"All Categories.Job Seekers.Farming & Veterinary CVs":"Farming & Veterinary CVs",
"All Categories.Jobs.Customer Service jobs":"Customer Service jobs",
"All Categories.Baby & Kids.Children's Furniture":"Children's Furniture",
"All Categories.Property.Other Property":"Other Property",
"All Categories.Automotive Vehicles.Bakkies & Cargo Vans":"Bakkies & Cargo Vans",
"All Categories.Electronics.Computers":"Computers",
"All Categories.Jobs.Security jobs":"Security jobs",
"All Categories.Jobs.Health & Beauty jobs":"Health & Beauty jobs",
"All Categories.Community.Musicians & Artists":"Musicians & Artists",
"All Categories.Job Seekers":"Job Seekers",
"All Categories.Events.Events, Gigs & Nightlife":"Events, Gigs & Nightlife",
"All Categories.Baby & Kids.Maternity & Pregnancy":"Maternity & Pregnancy",
"All Categories.Property.Commercial Properties":"Commercial Properties",
"All Categories.Automotive Vehicles.Farm Vehicles & Equipment":"Farm Vehicles & Equipment",
"All Categories.Electronics.Audio & Music Equipment":"Audio & Music Equipment",
"All Categories.Job Seekers.Manufacturing CVs":"Manufacturing CVs",
"All Categories.Job Seekers.Construction & Skilled trade CVs":"Construction & Skilled trade CVs",
"All Categories.Sports & Leisure.CD & DVD":"CD & DVD",
"All Categories.Pets.Cats & Kittens":"Cats & Kittens",
"All Categories.Jobs.Travel & Tourism jobs":"Travel & Tourism jobs",
"All Categories.Baby & Kids.Children's Clothing":"Children's Clothing",
"All Categories.Sports & Leisure.Sports, Bicycles & Fitness":"Sports, Bicycles & Fitness",
"All Categories.Boats & Watercraft.Kayaks & Paddle Boats":"Kayaks & Paddle Boats",
"All Categories.Community.Travel Partners & Companions":"Travel Partners & Companions",
"All Categories.Job Seekers.Retail CVs":"Retail CVs",
"All Categories.Jobs.Retail jobs":"Retail jobs",
"All Categories.Services.Party & Catering":"Party & Catering",
"All Categories.Sports & Leisure.Tickets":"Tickets",
"All Categories.Jobs.Teaching jobs":"Teaching jobs",
"All Categories.Boats & Watercraft":"Boats & Watercraft",
"All Categories.Job Seekers.Arts & Entertainment CVs":"Arts & Entertainment CVs",
"All Categories.Pets.Birds":"Birds",
"All Categories.Pets.Dogs & Puppies":"Dogs & Puppies",
"All Categories.Job Seekers.Accounting & Finance jobs":"Accounting & Finance jobs",
"All Categories.Jobs.Manufacturing Jobs":"Manufacturing Jobs",
"All Categories.Job Seekers.Advertising & Marketing CVs":"Advertising & Marketing CVs",
"All Categories.Job Seekers.Gardening & Landscaping CVs":"Gardening & Landscaping CVs",
"All Categories.Electronics.TV & DVD Equipment":"TV & DVD Equipment",
"All Categories.Services.Other services":"Other services",
"All Categories.Pets.Other Pets":"Other Pets",
"All Categories.Job Seekers.Sales & Telemarketing CVs":"Sales & Telemarketing CVs",
"All Categories.Fashion.Accessories":"Accessories",
"All Categories.Jobs":"Jobs",
"All Categories.Pets":"Pets",
"All Categories.Jobs.Construction & Skilled trade jobs":"Construction & Skilled trade jobs",
"All Categories.Jobs.Advertising & Marketing jobs":"Advertising & Marketing jobs",
"All Categories.Job Seekers.Human Resources CVs":"Human Resources CVs",
"All Categories.Home & Garden.Home decor & interiors":"Home decor & interiors",
"All Categories.Baby & Kids.Children's Gear & Safety":"Children's Gear & Safety",
"All Categories.Automotive Vehicles.Auto Parts & Accessories":"Auto Parts & Accessories",
"All Categories.Baby & Kids.Prams & Strollers":"Prams & Strollers",
"All Categories.Electronics.Video Games & Consoles":"Video Games & Consoles",
"All Categories.Home & Garden.Other":"Other",
"All Categories.Boats & Watercraft.Other Watercraft":"Other Watercraft",
"All Categories.Services.Building & Trades":"Building & Trades",
"All Categories.Jobs.Accounting & Finance jobs":"Accounting & Finance jobs",
"All Categories.Services.Travel Agents & Tours":"Travel Agents & Tours",
"All Categories.Business-to-Business":"Business-to-Business",
"All Categories.Job Seekers.Security CVs":"Security CVs",
"All Categories.Pets.Horses & Ponies":"Horses & Ponies",
"All Categories.Job Seekers.Banking Work CVs":"Banking Work CVs",
"All Categories.Fashion":"Fashion",
"All Categories.Community.Sports & Sports Partners":"Sports & Sports Partners",
"All Categories.Pets.Livestock & Poultry":"Livestock & Poultry",
"All Categories.Job Seekers.Hotel Work CVs":"Hotel Work CVs",
"All Categories.Home & Garden":"Home & Garden",
"All Categories.Jobs.Restaurant & Bar jobs":"Restaurant & Bar jobs",
"All Categories.Job Seekers.Travel & Tourism CVs":"Travel & Tourism CVs",
"All Categories.Electronics.Cameras & Video Cameras":"Cameras & Video Cameras",
"All Categories.Sports & Leisure.Other":"Other",
"All Categories.Electronics":"Electronics",
"All Categories.Automotive Vehicles.Motorcycles & Scooters":"Motorcycles & Scooters",
"All Categories.Community.Missed Connections":"Missed Connections",
"All Categories.Home & Garden.Furniture":"Furniture",
"All Categories.Business-to-Business.Office Equipment & Furniture":"Office Equipment & Furniture",
"All Categories.Boats & Watercraft.Boats & Jet Skis":"Boats & Jet Skis",
"All Categories.Jobs.Human Resources jobs":"Human Resources jobs",
"All Categories.Job Seekers.Restaurant & Bar CVs":"Restaurant & Bar CVs",
"All Categories.Services.Computer & IT Services":"Computer & IT Services",
"All Categories.Community.Classes & Adult Education":"Classes & Adult Education",
"All Categories.Services.Removals & Storage":"Removals & Storage",
"All Categories.Business-to-Business.Businesses For Sale":"Businesses For Sale",
"All Categories.Job Seekers.Housekeeping & Cleaning CVs":"Housekeeping & Cleaning CVs",
"All Categories.Baby & Kids.Nursery":"Nursery",
"All Categories.Services.Landscaping & Gardening services":"Landscaping & Gardening services",
"All Categories.Community.Carpool & Rideshare":"Carpool & Rideshare",
"All Categories.Services.Child Care & Education Services":"Child Care & Education Services",
"All Categories.Job Seekers.Health & Beauty CVs":"Health & Beauty CVs",
"All Categories.Community.Activities & Hobbies":"Activities & Hobbies",
"All Categories.Property.Flat Share & House Share":"Flat Share & House Share",
"All Categories.Services.Legal Services":"Legal Services",
"All Categories.Services.Health & Beauty services":"Health & Beauty services",
"All Categories.Business-to-Business.Other":"Other",
"All Categories.Boats & Watercraft.Boat Parts & Accessories":"Boat Parts & Accessories",
"All Categories.Jobs.Legal jobs":"Legal jobs",
"All Categories.Jobs.Farming & Veterinary jobs":"Farming & Veterinary jobs",
"All Categories.Automotive Vehicles.Motorcycle Parts & Accessories":"Motorcycle Parts & Accessories",
"All Categories.Jobs.Arts & Entertainment jobs":"Arts & Entertainment jobs",
"All Categories.Jobs.Part-time & Weekend jobs":"Part-time & Weekend jobs",
"All Categories.Boats & Watercraft.Yachts & Sailboats":"Yachts & Sailboats",
"All Categories.Events.Flea Market & Jumble Sale":"Flea Market & Jumble Sale",
"All Categories.Jobs.Gardening & Landscaping jobs":"Gardening & Landscaping jobs",
"All Categories.Sports & Leisure.Books & Games":"Books & Games",
"All Categories.Jobs.Computing & IT jobs":"Computing & IT jobs",
"All Categories.Property.Holiday Homes":"Holiday Homes",
"All Categories.Baby & Kids.Other":"Other",
"All Categories.Community.Lost & Found":"Lost & Found",
"All Categories.Job Seekers.Sports Club Work CVs":"Sports Club Work CVs",
"All Categories.Sports & Leisure.Camping Gear":"Camping Gear",
"All Categories.Jobs.General jobs":"General jobs",
"All Categories.Fashion.Other":"Other",
"All Categories.Job Seekers.Teaching CVs":"Teaching CVs",
}
