searcher_gumtree_location_map = {
"South Africa.Gauteng.Pretoria / Tshwane":"Pretoria / Tshwane",
"South Africa.KwaZulu-Natal.Drakensberg":"Drakensberg",
"South Africa.Gauteng.Sedibeng":"Sedibeng",
"South Africa.Western Cape.Cape Flats":"Cape Flats",
"South Africa.KwaZulu-Natal.Durban City":"Durban City",
"South Africa.Eastern Cape":"Eastern Cape",
"South Africa.Free State.Southern":"Southern",
"South Africa.KwaZulu-Natal.Midlands":"Midlands",
"South Africa.Limpopo.Polokwane":"Polokwane",
"South Africa.Gauteng":"Gauteng",
"South Africa.Free State.Goldfields":"Goldfields",
"South Africa.Eastern Cape.Wild Coast & Berg":"Wild Coast & Berg",
"South Africa.Free State.Northern":"Northern",
"South Africa.North West.Molema":"Molema",
"South Africa.Western Cape.Overberg":"Overberg",
"South Africa.Northern Cape.Namakwa":"Namakwa",
"South Africa.Gauteng.Johannesburg":"Johannesburg",
"South Africa.KwaZulu-Natal.North Suburbs":"North Suburbs",
"South Africa.KwaZulu-Natal.North Coast":"North Coast",
"South Africa.Northern Cape.Green Kalahari":"Green Kalahari",
"South Africa.Western Cape.Atlantic Seaboard":"Atlantic Seaboard",
"South Africa.Western Cape":"Western Cape",
"South Africa.Western Cape.Southern Peninsula":"Southern Peninsula",
"South Africa.KwaZulu-Natal.South Coast (Ugu)":"South Coast (Ugu)",
"South Africa.Eastern Cape.Western Region":"Western Region",
"South Africa.Gauteng.East Rand":"East Rand",
"South Africa.Mpumalanga":"Mpumalanga",
"South Africa.Northern Cape.Kalahari":"Kalahari",
"South Africa.Western Cape.West Coast":"West Coast",
"South Africa.Free State":"Free State",
"South Africa.Limpopo.Tzaneen":"Tzaneen",
"South Africa.North West.Bojanala":"Bojanala",
"South Africa.Limpopo":"Limpopo",
"South Africa.Free State.Eastern":"Eastern",
"South Africa.Western Cape.Northern Suburbs":"Northern Suburbs",
"South Africa.Mpumalanga.Wetland & Ermelo":"Wetland & Ermelo",
"South Africa.Northern Cape.Upper Karoo":"Upper Karoo",
"South Africa.Western Cape.Helderberg":"Helderberg",
"South Africa.Western Cape.Southern Suburbs":"Southern Suburbs",
"South Africa.Eastern Cape.Amatola":"Amatola",
"South Africa.KwaZulu-Natal.South Suburbs":"South Suburbs",
"South Africa.Limpopo.Musina":"Musina",
"South Africa.Mpumalanga.Ehlanzeni":"Ehlanzeni",
"South Africa.Limpopo.Phalaborwa":"Phalaborwa",
"South Africa.KwaZulu-Natal.West Suburbs":"West Suburbs",
"South Africa.Northern Cape.Hantam Karoo":"Hantam Karoo",
"South Africa.Gauteng.West Rand":"West Rand",
"South Africa.North West.Kaunda":"Kaunda",
"South Africa.North West":"North West",
"South Africa.Western Cape.Central Karoo":"Central Karoo",
"South Africa":"South Africa",
"South Africa.KwaZulu-Natal":"KwaZulu-Natal",
"South Africa.Northern Cape":"Northern Cape",
"South Africa.Western Cape.Cape Town":"Cape Town",
"South Africa.North West.Mompati":"Mompati",
"South Africa.Limpopo.Modimolle":"Modimolle",
"South Africa.Limpopo.Louis Trichardt":"Louis Trichardt",
"South Africa.Mpumalanga.Heartland - Cosmos Country":"Heartland - Cosmos Country",
"South Africa.Limpopo.Other":"Other",
"South Africa.Northern Cape.Diamond Fields":"Diamond Fields",
"South Africa.Western Cape.Cape Winelands":"Cape Winelands",
"South Africa.Western Cape.Eden":"Eden",
"South Africa.Mpumalanga.Highland":"Highland",
}
